#!/usr/bin/env bash
#
# ViMbAdmin ships Bootstrap 5. Bootstrap 5 renamed the plain `data-toggle=`/
# `data-dismiss=`/`data-target=` etc. JS-hook attributes to `data-bs-toggle=`/
# `data-bs-dismiss=`/`data-bs-target=` (the `data-bs-` prefix), and Bootstrap
# 5's own JS only wires up the prefixed spelling -- a template or view-JS
# string that still emits the bare `data-toggle="tab"` does not fail loudly,
# the widget just never initialises, so this scan is the guard for that class
# of breakage (VIM-A15.20, sibling of tests/lint-bs2-component-classes.sh and
# tests/lint-bs2-grid-classes.sh).
#
# Scope: own Smarty templates AND own view-JS that builds markup client-side
# via string concatenation, since a bare data-toggle/data-dismiss attribute
# embedded in a JS string literal is exactly as live a regression as one in a
# .phtml file (VIM-A15.19's history shows this exact class-vs-JS-string gap
# for component classes; this rename has the same two emit sites).
# Concretely: `application/views/**/*.phtml`, `application/views/**/js/*.js`,
# and the two first-party modal/UI scripts in `public/js`.
#
# Deliberately NOT scanned / NOT flagged:
#   - public/css/**, and vendored public/js/** assets -- vendored
#     Bootstrap and other third-party assets legitimately reference these
#     attributes, and the generated `min.bundle-v*` artifacts are never
#     hand-edited (regenerated by the project's minify tooling instead).
#   - `data-toggle-active` / `data-toggle-super` -- these are APP-OWN
#     attributes, not Bootstrap JS hooks (their click handlers select on
#     `[data-toggle-active]` directly), and must never be renamed to
#     `data-bs-toggle-active`. The token match below requires the attribute
#     name to end exactly at `toggle`/`dismiss`/`target`/etc, so a longer
#     app-own name is a different token and is not a match.
#
# Only the bare (non-`data-bs-`) spelling of the renamed Bootstrap JS-hook
# attributes is flagged: data-toggle, data-target, data-dismiss, data-ride,
# data-parent, data-spy, data-slide, data-slide-to, data-container,
# data-placement, data-trigger, data-offset, data-delay, data-html,
# data-interval, data-pause, data-wrap, data-backdrop, data-keyboard,
# data-focus, data-show.
#
# Exit 0 = clean, 1 = a bare Bootstrap data-* JS-hook attribute was found in
# an own template/view-JS emit site.
#
set -euo pipefail

cd "$(dirname "$0")/.."

if [ "${BASH_VERSINFO[0]:-0}" -lt 4 ]; then
  echo "  -> bash 4+ required for globstar; refusing to run a partial scan." >&2
  exit 1
fi

# Attribute names Bootstrap 5 renamed under the data-bs- prefix. Anchored so
# `data-toggle-active`/`data-toggle-super` (app-own) do not match `toggle`.
bs_data_attrs_re='data-(toggle|target|dismiss|ride|parent|spy|slide|slide-to|container|placement|trigger|offset|delay|html|interval|pause|wrap|backdrop|keyboard|focus|show)'
# Attribute name may be followed by optional whitespace before `=`; HTML permits
# `data-toggle = "tab"` and Bootstrap's own delegated handlers still match it.
bs_data_attrs_base="$bs_data_attrs_re"
bs_data_attrs_re="${bs_data_attrs_base}\\s*="

# scan_files FILE...
# Greps each file for a bare (non data-bs-) Bootstrap JS-hook attribute.
# Negative lookbehind equivalent done in two steps with grep -P: match the
# attribute name, then reject when it is immediately preceded by "-bs" (i.e.
# already `data-bs-toggle=`) or followed by more identifier chars (i.e.
# `data-toggle-active=`, an app-own attribute, not a Bootstrap hook).
scan_files() {
  local files=("$@") f fail=0 hit
  if [ "${#files[@]}" -eq 0 ]; then
    echo "  -> file list is empty." >&2
    return 1
  fi
  for f in "${files[@]}"; do
    while IFS= read -r hit; do
      [ -n "$hit" ] || continue
      echo "  Bootstrap data attribute missing bs- prefix in $f: $hit"
      fail=1
    done < <(grep -noP "(?<!-bs)\b${bs_data_attrs_re}" "$f" | grep -vP "${bs_data_attrs_base}-(active|super)\\s*=" || true)
  done
  return "$fail"
}

# self_test: prove the scan fires on reintroduced bare data-toggle/dismiss
# attributes (negative control), stays clean on data-bs- prefixed markup
# (positive control), and does not flag the app-own data-toggle-active/-super
# attributes.
self_test() {
  local tmpdir dirty clean status=0 expected_hits actual_hits

  tmpdir=$(mktemp -d)
  trap 'rm -rf "$tmpdir"' RETURN

  dirty="$tmpdir/dirty.phtml"
  clean="$tmpdir/clean.phtml"

  cat >"$dirty" <<'EOF'
<a href="#tab1" data-toggle="tab">Tab</a>
<a href="#" data-toggle="dropdown">Drop</a>
<button data-dismiss="modal">Close</button>
<div data-target="#myModal" data-toggle="modal">Open</div>
<a href="#" data-toggle = "tab">whitespace before = is valid HTML</a>
EOF

  cat >"$clean" <<'EOF'
<a href="#tab1" data-bs-toggle="tab">Tab</a>
<a href="#" data-bs-toggle="dropdown">Drop</a>
<button data-bs-dismiss="modal">Close</button>
<div data-bs-target="#myModal" data-bs-toggle="modal">Open</div>
<a href="#" data-toggle-active="1">app-own, not a Bootstrap hook</a>
<a href="#" data-toggle-super="1">app-own, not a Bootstrap hook</a>
<a href="#" data-toggle-active = "1">app-own, whitespace before =</a>
EOF

  echo "== self-test: negative control, reintroduced bare data-toggle/dismiss attrs must be caught =="
  # 6 seeded hits: tab, dropdown, modal(dismiss), target, toggle(modal), and
  # the whitespace-before-`=` spelling HTML permits.
  expected_hits=6
  actual_hits=$(scan_files "$dirty" | grep -c 'Bootstrap data attribute missing bs- prefix' || true)
  if [ "$actual_hits" -eq "$expected_hits" ]; then
    echo "  OK: all $expected_hits seeded regressions detected"
  else
    echo "  FAIL: expected $expected_hits hits in $dirty, got $actual_hits" >&2
    status=1
  fi

  echo "== self-test: Bootstrap 5 markup and app-own data-toggle-active/-super must not false-positive =="
  if scan_files "$clean" >/dev/null 2>&1; then
    echo "  OK: Bootstrap 5 template and app-own attributes reported no bare data attributes"
  else
    echo "  FAIL: scan reported a false positive on Bootstrap 5 markup or app-own attributes" >&2
    status=1
  fi

  echo "== self-test: view-JS string-concatenation negative control =="
  local jsdirty="$tmpdir/dirty-list.js"
  cat >"$jsdirty" <<'EOF'
var tab = "<li><a data-toggle=\"tab\"" + " href=\"#" + id + "\">" + title + "</a></li>";
elcode += "<a href=\"#\" class=\"btn dropdown-toggle\" data-toggle=\"dropdown\" >";
EOF
  local js_expected_hits=2 js_actual_hits
  js_actual_hits=$(scan_files "$jsdirty" | grep -c 'Bootstrap data attribute missing bs- prefix' || true)
  if [ "$js_actual_hits" -eq "$js_expected_hits" ]; then
    echo "  OK: all $js_expected_hits seeded view-JS regressions detected"
  else
    echo "  FAIL: expected $js_expected_hits hits in $jsdirty, got $js_actual_hits" >&2
    status=1
  fi

  local jsclean="$tmpdir/clean-list.js"
  cat >"$jsclean" <<'EOF'
var tab = "<li><a data-bs-toggle=\"tab\"" + " href=\"#" + id + "\">" + title + "</a></li>";
elcode += "<a href=\"#\" class=\"btn dropdown-toggle\" data-bs-toggle=\"dropdown\" >";
EOF
  if scan_files "$jsclean" >/dev/null 2>&1; then
    echo "  OK: Bootstrap 5 view-JS reported no bare data attributes"
  else
    echo "  FAIL: scan reported a false positive on Bootstrap 5 view-JS" >&2
    status=1
  fi

  return "$status"
}

shopt -s nullglob globstar
files=(application/views/**/*.phtml application/views/**/js/*.js public/js/850-vimbadmin.modals.js public/js/990-vimbadmin.js)

echo "== own templates/view-JS must use data-bs- prefixed Bootstrap JS-hook attributes =="

if ! self_test; then
  echo "  -> lint self-test failed: the scan itself is broken, refusing to trust its verdict" >&2
  exit 1
fi

if [ "${#files[@]}" -eq 0 ]; then
  echo "  -> Own template inventory is empty." >&2
  exit 1
fi

missing=()
for f in "${files[@]}"; do
  [ -r "$f" ] || missing+=("$f")
done
if [ "${#missing[@]}" -ne 0 ]; then
  echo "  -> Cannot read ${#missing[@]} expected input file(s); refusing to report a partial scan as clean:" >&2
  printf '       %s\n' "${missing[@]}" >&2
  exit 1
fi

if scan_files "${files[@]}"; then
  echo "  OK: no bare Bootstrap data-* JS-hook attribute in own templates (${#files[@]} templates scanned)"
  exit 0
else
  exit 1
fi
