{if isset( $config.use_minified_js ) and $config.use_minified_js}
    <script type="text/javascript" src="{genUrl}/js/min.bundle-v29.js"></script>
{else}
    <script type="text/javascript" src="{genUrl}/js/120-vimbadmin.validation.js"></script>
    <script type="text/javascript" src="{genUrl}/js/150-datatables.js"></script>
    <script type="text/javascript" src="{genUrl}/js/151-datatables.ext.js"></script>
    <script type="text/javascript" src="{genUrl}/js/152-datatables.bootstrap5.js"></script>
    <script type="text/javascript" src="{genUrl}/js/800-bootstrap.js"></script>
    <script type="text/javascript" src="{genUrl}/js/850-vimbadmin.modals.js"></script>
    <script type="text/javascript" src="{genUrl}/js/910-vimbadmin.functions.js"></script>
    <script type="text/javascript" src="{genUrl}/js/990-vimbadmin.js"></script>
{/if}
