<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;
use UnexpectedValueException;

/**
 * Admin
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends EntityRepository<\Entities\Admin>
 */
class Admin extends EntityRepository
{
    /**
     * Replace an authenticated credential only if it is still the exact hash
     * that was verified. A concurrent password reset wins harmlessly.
     */
    public function compareAndSwapPassword(\Entities\Admin $admin, string $verified, string $replacement): bool
    {
        $affected = $this->getEntityManager()->getConnection()->executeStatement(
            'UPDATE admin SET password = ? WHERE id = ? AND BINARY password = BINARY ?',
            [ $replacement, $admin->getId(), $verified ],
        );

        return $affected === 1;
    }

    /**
     * Count the number of admins.
     *
     * Return count of all admins.
     *
     * Doctrine returns the driver's scalar value unchanged.
     *
     * @return bool|float|int|string|null
     */
    public function getCount()
    {
        return $this->getEntityManager()->createQuery(
            "SELECT COUNT( a.id ) FROM \\Entities\\Admin a"
        )
            ->getSingleScalarResult();
    }

    /**
     * Finds all admins who are not assigned with domain.
     *
     * Builds an array of 'id' => 'username', appending " (inactive)" to the
     * username when the admin is not active. Super admins and admins already
     * assigned to the domain are excluded in the query itself.
     *
     * @param \Entities\Domain $domain Domain to look for admins
     * @return array<int|string,string|null>
     */
    public function getNotAssignedForDomain($domain)
    {
        $dql = 'SELECT a.id AS id, a.username AS username, a.active AS active'
            . ' FROM \\Entities\\Admin a'
            . ' WHERE a.super = false'
            . ' AND a NOT IN ('
            .     'SELECT a2 FROM \\Entities\\Domain d JOIN d.Admins a2 WHERE d = ?1'
            . ')';

        return self::mapNotAssignedRows($this->runNotAssignedQuery($dql, $domain));
    }

    /**
     * Execute {@see getNotAssignedForDomain}'s DQL and return its scalar rows.
     *
     * Isolated as a seam so tests can substitute fixture rows and pin the
     * mapping and exclusion contracts without a live database. Production
     * behaviour is unchanged: the DQL, its parameter and the hydration mode
     * are all fixed by the caller above.
     *
     * @param string $dql The not-assigned query
     * @param \Entities\Domain $domain Bound to parameter 1
     * @return mixed Doctrine::getArrayResult() output
     */
    protected function runNotAssignedQuery($dql, $domain)
    {
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter(1, $domain);

        return $query->getArrayResult();
    }

    /**
     * Map the id/username/active scalar rows from {@see getNotAssignedForDomain}'s
     * query into an id => username map, appending " (inactive)" when the admin
     * is not active. Kept as a pure static helper so the row-shape contract can
     * be pinned by tests without standing up a Doctrine query.
     *
     * @param mixed $rows Doctrine::getArrayResult() output
     * @return array<int|string,string|null>
     */
    public static function mapNotAssignedRows($rows)
    {
        if (!is_array($rows)) {
            throw new UnexpectedValueException('Admin not-assigned query result must be an array.');
        }

        $adminNames = [];
        foreach ($rows as $row) {
            [ $id, $username, $active ] = self::requiredNotAssignedRowShape($row);
            $adminNames[ $id ] = $active ? $username : $username . " (inactive)";
        }

        return $adminNames;
    }

    /**
     * @param mixed $row One element of getArrayResult() output
     * @return array{0:int|string,1:string,2:mixed}
     */
    private static function requiredNotAssignedRowShape($row)
    {
        if (!is_array($row) || !array_key_exists('id', $row)
            || !(is_int($row['id']) || is_string($row['id']))
            || !isset($row['username']) || !is_string($row['username'])
            || !array_key_exists('active', $row)) {
            throw new UnexpectedValueException('Admin not-assigned query row has an invalid shape.');
        }

        return [ $row['id'], $row['username'], $row['active'] ];
    }
}
