<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;
use ViMbAdmin\Kernel\DataTable\DataTableQuery;

/**
 * Alias
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends EntityRepository<\Entities\Alias>
 */
class Alias extends EntityRepository
{
    private static function requiredAliasFilter(mixed $filter): string
    {
        if (!is_string($filter)) {
            throw new \UnexpectedValueException('Alias filter must be a string.');
        }
        return $filter;
    }

    /**
     * @param mixed $rows
     * @return array<int,array{id:int|string,address:string,goto:string,active:bool,domain:string}>
     */
    private static function requiredAliasListRows(mixed $rows): array
    {
        if (!is_array($rows)) {
            throw new \UnexpectedValueException('Alias query result must be an array.');
        }

        $result = [];
        foreach ($rows as $key => $row) {
            if (!is_int($key) || !is_array($row)
                || !array_key_exists('id', $row) || (!is_int($row['id']) && !is_string($row['id']))
                || !isset($row['address']) || !is_string($row['address'])
                || !isset($row['goto']) || !is_string($row['goto'])
                || !array_key_exists('active', $row) || !is_bool($row['active'])
                || !isset($row['domain']) || !is_string($row['domain'])) {
                throw new \UnexpectedValueException('Alias query row has an invalid shape.');
            }
            $result[$key] = [
                'id' => $row['id'], 'address' => $row['address'], 'goto' => $row['goto'],
                'active' => $row['active'], 'domain' => $row['domain'],
            ];
        }
        return $result;
    }

    /**
     * Loads aliases for mailbox.
     *
     * Selects aliases where the address is not equal to goto (i.e. it's not a
     * mailbox alias), and goto equals the mailbox username. If include
     * mailbox aliases is true then it does also return those. If admin
     * is not super then it checks if admin is linked with the domain.
     *
     * @param \Entities\Mailbox $mailbox Mailbox for alias filtering.
     * @param \Entities\Admin|null $admin Admin for checking privileges, or null for a trusted system context.
     * @param bool              $ima     If set to true, then it include and where address equals to goto.
     * @return \Entities\Alias[]
     */
    public function loadForMailbox($mailbox, $admin, $ima = false)
    {
        $username = $mailbox->requiredUsername();
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('a')
                ->from('\\Entities\\Alias', 'a')
                ->where('a.goto = ?1')
                ->setParameter(1, $username);

        if (!$ima) {
            $qb->andWhere('a.address != a.goto');
        }

        // $admin === null is trusted system context (CLI / queue runner): no
        // per-admin domain scoping, same as a super-admin. Guard the null
        // before calling isSuper() or the queue delete crashes with
        // "Call to a member function isSuper() on null".
        if ($admin !== null && !$admin->isSuper()) {
            $qb->leftJoin('a.Domain', 'd')
                ->leftJoin('d.Admins', 'd2a')
                ->andWhere('d2a = :admin')
                ->setParameter('admin', $admin);
        }

        return \ViMbAdmin\Kernel\Doctrine\ResultValidator::entityList(
            $qb->getQuery()->getResult(),
            \Entities\Alias::class,
            'Alias mailbox query'
        );
    }

    /**
     * Loads aliases with mailbox.
     *
     * Selects aliases where address not equal to goto, and goto not equals to
     * mailbox username, but goto has mailbox username. If admin is not super
     * then it checks if admin have have linked with domain.
     *
     * @param \Entities\Mailbox $mailbox Mailbox for alias filtering.
     * @param \Entities\Admin|null $admin Admin for checking privileges, or null for a trusted system context.
     * @return \Entities\Alias[]
     */
    public function loadWithMailbox($mailbox, $admin)
    {
        $username = $mailbox->requiredUsername();
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a')
            ->from('\\Entities\\Alias', 'a')
            ->where($qb->expr()->andX(
                'a.address != a.goto',
                'a.goto != ?1',
                $qb->expr()->orX(
                    'a.goto like ?2',
                    'a.goto like ?3',
                    'a.goto like ?4'
                )
            ))
            ->setParameter(1, $username)
            ->setParameter(2, '%,' . $username . ',%')
            ->setParameter(3, '%,' . $username)
            ->setParameter(4, $username . ',%');

        // null admin = trusted system context (queue runner); no scoping.
        if ($admin !== null && !$admin->isSuper()) {
            $qb->leftJoin('a.Domain', 'd')
                ->leftJoin('d.Admins', 'd2a')
                ->andWhere('d2a = :admin')
                ->setParameter('admin', $admin);
        }

        return \ViMbAdmin\Kernel\Doctrine\ResultValidator::entityList(
            $qb->getQuery()->getResult(),
            \Entities\Alias::class,
            'Alias mailbox-membership query'
        );
    }

    /**
     * Load aliases for alias list .
     *
     * Loads aliases for alias list, if admin is not super, it will select aliases
     * only from domains which are linked with admin. If domain is set it will select
     * aliases only for given domain, and if ima set to false then it will select all
     * aliases where goto not equal to address that mean non mailbox aliases.
     *
     * @param \Entities\Admin  $admin  Admin for filtering mailboxes.
     * @param \Entities\Domain $domain Domain for filtering mailboxes.
     * @param bool             $ima    Include mailbox aliases flag.
     * @return array<int,array{id:int|string,address:string,goto:string,active:bool,domain:string}>
     */
    public function loadForAliasList($admin, $domain = null, $ima = false)
    {
        return self::requiredAliasListRows(
            $this->aliasListQuery($admin, $domain, $ima)->getQuery()->getArrayResult()
        );
    }

    private function aliasListQuery(\Entities\Admin $admin, \Entities\Domain|int|null $domain, bool $ima): \Doctrine\ORM\QueryBuilder
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('a.id as id , a.address as address, a.goto as goto, a.active as active, d.domain as domain')
            ->from('\\Entities\\Alias', 'a')
            ->join('a.Domain', 'd');

        if (!$admin->isSuper()) {
            $qb->join('d.Admins', 'd2a')
                ->where('d2a = ?1')
                ->setParameter(1, $admin);
        }

        if ($domain) {
            $qb->andWhere('a.Domain = ?2')
                ->setParameter(2, $domain);
        }

        if (!$ima) {
            $qb->andWhere("a.address != a.goto");
        }

        return $qb;
    }

    /**
     * One page of the alias list for DataTables server-side processing.
     *
     * Same scope as {@see loadForAliasList} (domain/admin filtered, mailbox
     * aliases excluded unless $ima) but searched, ordered and LIMIT/OFFSET in
     * SQL, returning the page plus total / filtered counts. Search binds a
     * parameter; the sort field is whitelisted by the caller.
     *
     * @param \Entities\Admin       $admin
     * @param \Entities\Domain|null $domain
     * @return array{rows: array<int,array{id:int|string,address:string,goto:string,active:bool,domain:string}>, total: int, filtered: int}
     */
    public function pagedForAliasList($admin, $domain, bool $ima, string $search, bool $contains, string $sortField, string $sortDir, int $start, int $length)
    {
        $base = function () use ($admin, $domain, $ima): \Doctrine\ORM\QueryBuilder {
            $qb = $this->getEntityManager()->createQueryBuilder()
                ->from('\\Entities\\Alias', 'a')
                ->join('a.Domain', 'd');

            if (!$admin->isSuper()) {
                $qb->join('d.Admins', 'd2a')->andWhere('d2a = :admin')->setParameter('admin', $admin);
            }

            if ($domain) {
                $qb->andWhere('a.Domain = :domain')->setParameter('domain', $domain);
            }

            if (!$ima) {
                $qb->andWhere('a.address != a.goto');
            }

            return $qb;
        };

        $applySearch = function (\Doctrine\ORM\QueryBuilder $qb) use ($search, $contains): \Doctrine\ORM\QueryBuilder {
            if ($search !== '') {
                $qb->andWhere('( a.address LIKE :s OR a.goto LIKE :s OR d.domain LIKE :s )')
                   ->setParameter('s', DataTableQuery::likePattern($search, $contains));
            }
            return $qb;
        };

        // Unfiltered total stable per scope (ima changes it) -> cache briefly.
        $scopeKey = 'vimb_total_al_' . $admin->getId() . '_' . ($domain ? $domain->requiredId() : 0) . '_' . (int) $ima;
        $total    = (int) $base()->select('COUNT(DISTINCT a.id)')->getQuery()
            ->enableResultCache(30, $scopeKey)->getSingleScalarResult();
        $filtered = $search === ''
            ? $total
            : (int) $applySearch($base())->select('COUNT(DISTINCT a.id)')->getQuery()->getSingleScalarResult();

        $sortMap = [ 'address' => 'a.address', 'domain' => 'd.domain', 'active' => 'a.active', 'goto' => 'a.goto' ];
        $orderBy = $sortMap[ $sortField ] ?? 'a.address';

        $rows = self::requiredAliasListRows($applySearch($base())
            ->select('a.id as id, a.address as address, a.goto as goto, a.active as active, d.domain as domain')
            ->orderBy($orderBy, $sortDir === 'DESC' ? 'DESC' : 'ASC')
            ->setFirstResult(max(0, $start))
            ->setMaxResults(max(1, $length))
            ->getQuery()->getArrayResult());

        return [ 'rows' => $rows, 'total' => $total, 'filtered' => $filtered ];
    }

    /**
     * Filtered alias data array (used by the MailboxAutomaticAliases plugin to
     * look an alias up by name). `*` prefix → contains-match, else prefix-match.
     *
     * NB: the filter is bound as a parameter (the old version interpolated it
     * straight into the DQL — a DQL-injection footgun). The list pages no longer
     * use this; they use {@see pagedForAliasList} (DataTables server-side).
     *
     * @param string                $filter
     * @param \Entities\Admin       $admin
     * @param \Entities\Domain|int|null $domain
     * @param bool                     $ima
     * @return array<int,array{id:int|string,address:string,goto:string,active:bool,domain:string}>
     */
    public function filterForAliasList($filter, $admin, $domain = null, $ima = false)
    {
        return self::requiredAliasListRows(
            $this->filteredAliasListQuery($filter, $admin, $domain, $ima)->getQuery()->getArrayResult()
        );
    }

    private function filteredAliasListQuery(mixed $filter, \Entities\Admin $admin, \Entities\Domain|int|null $domain, bool $ima): \Doctrine\ORM\QueryBuilder
    {
        $filter  = str_replace("'", "", self::requiredAliasFilter($filter));
        $pattern = (strpos($filter, '*') === 0)
            ? '%' . addcslashes(substr($filter, 1), '%_\\') . '%'
            : addcslashes($filter, '%_\\') . '%';

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('a.id as id , a.address as address, a.goto as goto, a.active as active, d.domain as domain')
            ->from('\\Entities\\Alias', 'a')
            ->join('a.Domain', 'd')
            ->where('( a.goto LIKE :s OR a.address LIKE :s OR d.domain LIKE :s )')
            ->setParameter('s', $pattern);

        if (!$admin->isSuper()) {
            $qb->join('d.Admins', 'd2a')->andWhere('d2a = :admin')->setParameter('admin', $admin);
        }

        if ($domain) {
            $qb->andWhere('a.Domain = :domain')->setParameter('domain', $domain);
        }

        if (!$ima) {
            $qb->andWhere('a.address != a.goto');
        }

        return $qb;
    }

}
