<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Alias
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Alias extends EntityRepository
{

    /**
     * Loads aliases for mailbox.
     *
     * Selects aliases where the address is not equal to goto (i.e. it's not a
     * mailbox alias), and goto equals the mailbox username. If include
     * mailbox aliases is true then it does also return those. If admin
     * is not super then it checks if admin is linked with the domain.
     *
     * @param \Entities\Mailbox $mailbox Mailbox for alias filtering.
     * @param \Entities\Admin   $admin   Admin for checking privileges.
     * @param bool              $ima     If set to true, then it include and where address equals to goto.
     * @return \Entities\Alias[]
     */
    public function loadForMailbox( $mailbox, $admin, $ima = false )
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select( 'a' )
                ->from( '\\Entities\\Alias', 'a' )
                ->where( 'a.goto = ?1' )
                ->setParameter( 1, $mailbox->getUsername() );

        if( !$ima )
            $qb->andWhere( 'a.address != a.goto' );

        // $admin === null is trusted system context (CLI / queue runner): no
        // per-admin domain scoping, same as a super-admin. Guard the null
        // before calling isSuper() or the queue delete crashes with
        // "Call to a member function isSuper() on null".
        if( $admin !== null && !$admin->isSuper() )
        {
            $qb->leftJoin( 'a.Domain', 'd' )
                ->leftJoin( 'd.Admins', 'd2a' )
                ->andWhere( 'd2a = :admin' )
                ->setParameter( 'admin', $admin );
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * Loads aliases with mailbox.
     *
     * Selects aliases where address not equal to goto, and goto not equals to
     * mailbox username, but goto has mailbox username. If admin is not super
     * then it checks if admin have have linked with domain.
     *
     * @param \Entities\Mailbox $mailbox Mailbox for alias filtering.
     * @param \Entities\Admin   $admin   Admin for checking privileges.
     * @return \Entities\Alias[]
     */
    public function loadWithMailbox( $mailbox, $admin )
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select( 'a' )
            ->from( '\\Entities\\Alias', 'a' )
            ->where($qb->expr()->andX(
                'a.address != a.goto',
                'a.goto != ?1',
                $qb->expr()->orX(
                    'a.goto like ?2',
                    'a.goto like ?3',
                    'a.goto like ?4'
                )
            ))
            ->setParameter( 1, $mailbox->getUsername() )
            ->setParameter( 2, '%,' . $mailbox->getUsername() . ',%')
            ->setParameter( 3, '%,' . $mailbox->getUsername())
            ->setParameter( 4, $mailbox->getUsername() . ',%');

        // null admin = trusted system context (queue runner); no scoping.
        if( $admin !== null && !$admin->isSuper() )
        {
            $qb->leftJoin( 'a.Domain', 'd' )
                ->leftJoin( 'd.Admins', 'd2a' )
                ->andWhere( 'd2a = :admin' )
                ->setParameter( 'admin', $admin );
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * Load aliases for alias list .
     *
     * Loads aliases for alias list, if admin is not super, it will select aliases
     * only from domains which are linked with admin. If domain is set it will select
     * aliases only for given domain, and if ima set to false then it will select all
     * aliases where goto not equal to address that mean non mailbox aliases.
     *
     * @param \Entities\Admin  $admin  Admin for filtering mailboxes.
     * @param \Entities\Domain $domain Domain for filtering mailboxes.
     * @param bool             $ima    Include mailbox aliases flag.
     * @return array
     */
    public function loadForAliasList( $admin, $domain = null, $ima = false )
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select( 'a.id as id , a.address as address, a.goto as goto, a.active as active, d.domain as domain' )
            ->from( '\\Entities\\Alias', 'a' )
            ->join( 'a.Domain', 'd' );

        if( !$admin->isSuper() )
            $qb->join( 'd.Admins', 'd2a' )
                ->where( 'd2a = ?1' )
                ->setParameter( 1, $admin );

        if( $domain )
            $qb->andWhere( 'a.Domain = ?2' )
                ->setParameter( 2, $domain );

        if( !$ima )
            $qb->andWhere( "a.address != a.goto" );
        return $qb->getQuery()->getArrayResult();
    }

    /**
     * One page of the alias list for DataTables server-side processing.
     *
     * Same scope as {@see loadForAliasList} (domain/admin filtered, mailbox
     * aliases excluded unless $ima) but searched, ordered and LIMIT/OFFSET in
     * SQL, returning the page plus total / filtered counts. Search binds a
     * parameter; the sort field is whitelisted by the caller.
     *
     * @param \Entities\Admin       $admin
     * @param \Entities\Domain|null $domain
     * @return array{rows: array, total: int, filtered: int}
     */
    public function pagedForAliasList( $admin, $domain, bool $ima, string $search, string $sortField, string $sortDir, int $start, int $length )
    {
        $base = function() use ( $admin, $domain, $ima ) {
            $qb = $this->getEntityManager()->createQueryBuilder()
                ->from( '\\Entities\\Alias', 'a' )
                ->join( 'a.Domain', 'd' );

            if( !$admin->isSuper() )
                $qb->join( 'd.Admins', 'd2a' )->andWhere( 'd2a = :admin' )->setParameter( 'admin', $admin );

            if( $domain )
                $qb->andWhere( 'a.Domain = :domain' )->setParameter( 'domain', $domain );

            if( !$ima )
                $qb->andWhere( 'a.address != a.goto' );

            return $qb;
        };

        $applySearch = function( $qb ) use ( $search ) {
            if( $search !== '' )
                $qb->andWhere( '( a.address LIKE :s OR a.goto LIKE :s OR d.domain LIKE :s )' )
                   ->setParameter( 's', '%' . addcslashes( $search, '%_\\' ) . '%' );
            return $qb;
        };

        $total    = (int) $base()->select( 'COUNT(DISTINCT a.id)' )->getQuery()->getSingleScalarResult();
        $filtered = (int) $applySearch( $base() )->select( 'COUNT(DISTINCT a.id)' )->getQuery()->getSingleScalarResult();

        $sortMap = [ 'address' => 'a.address', 'domain' => 'd.domain', 'active' => 'a.active', 'goto' => 'a.goto' ];
        $orderBy = $sortMap[ $sortField ] ?? 'a.address';

        $rows = $applySearch( $base() )
            ->select( 'a.id as id, a.address as address, a.goto as goto, a.active as active, d.domain as domain' )
            ->orderBy( $orderBy, $sortDir === 'DESC' ? 'DESC' : 'ASC' )
            ->setFirstResult( max( 0, $start ) )
            ->setMaxResults( max( 1, $length ) )
            ->getQuery()->getArrayResult();

        return [ 'rows' => $rows, 'total' => $total, 'filtered' => $filtered ];
    }

    /**
     * Return filtered alias data array
     *
     * Use filter to filter aliases by address or goto or domain. If filter
     * starts with * it will be replaced with % to meet sql requirements. At
     * the end % will be added to all strings. So filter 'man' will bicome
     * 'man%' and will look for man, manual and iffilter '*man' it wil bicome
     * '%man%' and will look for records like human, humanity, man, manual.
     *
     * @param string           $filter Flter for mailboxes
     * @param \Entities\Admin  $admin  Admin for filtering mailboxes.
     * @param \Entities\Domain $domain Domain for filtering mailboxes.
     * @param bool             $ima    Include mailbox aliases flag.
     * @return array
     */
    public function filterForAliasList( $filter, $admin, $domain = null,  $ima = false  )
    {
        $filter = str_replace ( "'" , "" , $filter );

        if( strpos( $filter, "*" ) === 0 )
            $filter = '%' . substr( $filter, 1 );

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select( 'a.id as id , a.address as address, a.goto as goto, a.active as active, d.domain as domain' )
            ->from( '\\Entities\\Alias', 'a' )
            ->join( 'a.Domain', 'd' )
            ->where( "( a.goto LIKE '{$filter}%' OR a.address LIKE '{$filter}%' OR d.domain LIKE '{$filter}%')" );

        if( !$admin->isSuper() )
            $qb->join( 'd.Admins', 'd2a' )
                ->andWhere( 'd2a = ?1' )
                ->setParameter( 1, $admin );

        if( $domain )
            $qb->andWhere( 'a.Domain = ?2' )
                ->setParameter( 2, $domain );

        if( !$ima )
            $qb->andWhere( "a.address != a.goto" );

        return $qb->getQuery()->getArrayResult();
    }
}
