<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;
use ViMbAdmin\Kernel\DataTable\DataTableQuery;

/**
 * Archive
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends EntityRepository<\Entities\Archive>
 */
class Archive extends EntityRepository
{
    /**
     * @param mixed $rows
     * @return array<int,array{id:mixed,username:mixed,status:mixed,archived_at:mixed,autoprune:mixed,maildir_size:mixed,domain:mixed,user_exists:mixed}>
     */
    private static function requiredArchiveListRows(mixed $rows): array
    {
        if (!is_array($rows)) {
            throw new \UnexpectedValueException('Archive query result must be an array.');
        }

        $result = [];
        $fields = ['id', 'username', 'status', 'archived_at', 'autoprune', 'maildir_size', 'domain', 'user_exists'];
        foreach ($rows as $key => $row) {
            if (!is_int($key) || !is_array($row)) {
                throw new \UnexpectedValueException('Archive query row has an invalid shape.');
            }
            foreach ($fields as $field) {
                if (!array_key_exists($field, $row)) {
                    throw new \UnexpectedValueException('Archive query row has an invalid shape.');
                }
            }
            $result[$key] = [
                'id' => $row['id'], 'username' => $row['username'], 'status' => $row['status'],
                'archived_at' => $row['archived_at'], 'autoprune' => $row['autoprune'],
                'maildir_size' => $row['maildir_size'], 'domain' => $row['domain'],
                'user_exists' => $row['user_exists'],
            ];
        }
        return $result;
    }
    /**
     * Load archives for archive list .
     *
     * If admin is super he gets all mailboxes.
     *
     * @param \Entities\Admin $admin Admin for filtering mailboxes.
     * @param \Entities\Domain|null $domain Domain for filtering mailboxes.
     * @return array<int,array{id:mixed,username:mixed,status:mixed,archived_at:mixed,autoprune:mixed,maildir_size:mixed,domain:mixed,user_exists:mixed}>
     */
    public function loadForArchiveList($admin, $domain = null)
    {
        return self::requiredArchiveListRows(
            $this->archiveListQuery($admin, $domain)->getQuery()->getArrayResult()
        );
    }

    private function archiveListQuery(\Entities\Admin $admin, ?\Entities\Domain $domain): \Doctrine\ORM\QueryBuilder
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('a.id as id , a.username as username, a.status as status, '
                    . 'a.archived_at as archived_at, a.autoprune as autoprune, '
                    . 'a.maildir_size as maildir_size, '
                    . 'd.domain as domain, '
                    . '(CASE WHEN m.id IS NULL THEN 0 ELSE 1 END) as user_exists')
            ->from('\\Entities\\Archive', 'a')
            ->join('a.Domain', 'd')
            // LEFT JOIN the live mailbox by username so the list can show whether
            // the account still exists (ARCHIVE keeps it, DELETE removes it).
            ->leftJoin('\\Entities\\Mailbox', 'm', \Doctrine\ORM\Query\Expr\Join::WITH, 'm.username = a.username');

        if (!$admin->isSuper()) {
            $qb->join('d.Admins', 'd2a')
                ->where('d2a = :admin')
                ->setParameter('admin', $admin);
        }

        if ($domain) {
            $qb->andWhere('a.Domain = ?2')
                ->setParameter(2, $domain);
        }

        return $qb;
    }

    /**
     * One page of the archive list for DataTables server-side processing.
     *
     * Same fields/scope as {@see loadForArchiveList} (incl. the live-mailbox
     * existence CASE) but searched, ordered and LIMIT/OFFSET in SQL, returning
     * the page plus total / filtered counts. Search binds a parameter; the sort
     * field is whitelisted by the caller.
     *
     * @param \Entities\Admin       $admin
     * @param \Entities\Domain|null $domain
     * @return array{rows: array<int,array{id:mixed,username:mixed,status:mixed,archived_at:mixed,autoprune:mixed,maildir_size:mixed,domain:mixed,user_exists:mixed}>, total: int, filtered: int}
     */
    public function pagedForArchiveList($admin, $domain, string $search, bool $contains, string $sortField, string $sortDir, int $start, int $length)
    {
        $base = function () use ($admin, $domain): \Doctrine\ORM\QueryBuilder {
            $qb = $this->getEntityManager()->createQueryBuilder()
                ->from('\\Entities\\Archive', 'a')
                ->join('a.Domain', 'd')
                ->leftJoin('\\Entities\\Mailbox', 'm', \Doctrine\ORM\Query\Expr\Join::WITH, 'm.username = a.username');

            if (!$admin->isSuper()) {
                $qb->join('d.Admins', 'd2a')->andWhere('d2a = :admin')->setParameter('admin', $admin);
            }

            if ($domain) {
                $qb->andWhere('a.Domain = :domain')->setParameter('domain', $domain);
            }

            return $qb;
        };

        $applySearch = function (\Doctrine\ORM\QueryBuilder $qb) use ($search, $contains): \Doctrine\ORM\QueryBuilder {
            if ($search !== '') {
                $qb->andWhere('( a.username LIKE :s OR d.domain LIKE :s )')
                   ->setParameter('s', DataTableQuery::likePattern($search, $contains));
            }
            return $qb;
        };

        // Unfiltered total stable per scope -> cache briefly.
        $scopeKey = 'vimb_total_arc_' . $admin->getId() . '_' . ($domain ? $domain->requiredId() : 0);
        $total    = (int) $base()->select('COUNT(DISTINCT a.id)')->getQuery()
            ->enableResultCache(30, $scopeKey)->getSingleScalarResult();
        $filtered = $search === ''
            ? $total
            : (int) $applySearch($base())->select('COUNT(DISTINCT a.id)')->getQuery()->getSingleScalarResult();

        $sortMap = [ 'username' => 'a.username', 'status' => 'a.status', 'domain' => 'd.domain', 'archived_at' => 'a.archived_at' ];
        $orderBy = $sortMap[ $sortField ] ?? 'a.archived_at';

        $rows = self::requiredArchiveListRows($applySearch($base())
            ->select('a.id as id, a.username as username, a.status as status, '
                    . 'a.archived_at as archived_at, a.autoprune as autoprune, '
                    . 'a.maildir_size as maildir_size, d.domain as domain, '
                    . '(CASE WHEN m.id IS NULL THEN 0 ELSE 1 END) as user_exists')
            ->orderBy($orderBy, $sortDir === 'ASC' ? 'ASC' : 'DESC')
            ->setFirstResult(max(0, $start))
            ->setMaxResults(max(1, $length))
            ->getQuery()->getArrayResult());

        return [ 'rows' => $rows, 'total' => $total, 'filtered' => $filtered ];
    }

    /**
     * Archives flagged autoprune=1. With $before set, only those archived at or
     * before that cutoff (expired); without it, every autoprune-on archive.
     * Returns Archive entities (the prune needs their maildir dest + row).
     *
     * @param \DateTime|null $before  expiry cutoff (null = all autoprune rows)
     * @return \Entities\Archive[]
     */
    public function findAutoprune(?\DateTime $before = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('a')
            ->from('\\Entities\\Archive', 'a')
            ->where('a.autoprune = true');

        if ($before !== null) {
            $qb->andWhere('a.archived_at <= :before')
               ->setParameter('before', $before);
        }

        return \ViMbAdmin\Kernel\Doctrine\ResultValidator::entityList(
            $qb->getQuery()->getResult(),
            \Entities\Archive::class,
            'Archive autoprune query'
        );
    }
}
