<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Archive
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Archive extends EntityRepository
{
    /**
     * Load archives for archive list .
     *
     * If admin is super he gets all mailboxes.
     *
     * @param \Entities\Admin $admin Admin for filtering mailboxes.
     * @param \Entities\Domain $domain Domain for filtering mailboxes.
     * @return array
     */
    public function loadForArchiveList( $admin, $domain = null )
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select( 'a.id as id , a.username as username, a.status as status, '
                    . 'a.archived_at as archived_at, a.autoprune as autoprune, '
                    . 'd.domain as domain, '
                    . '(CASE WHEN m.id IS NULL THEN 0 ELSE 1 END) as user_exists' )
            ->from( '\\Entities\\Archive', 'a' )
            ->join( 'a.Domain', 'd' )
            // LEFT JOIN the live mailbox by username so the list can show whether
            // the account still exists (ARCHIVE keeps it, DELETE removes it).
            ->leftJoin( '\\Entities\\Mailbox', 'm', \Doctrine\ORM\Query\Expr\Join::WITH, 'm.username = a.username' );

        if( !$admin->isSuper() )
            $qb->join( 'd.Admins', 'd2a' )
                ->where( 'd2a = :admin' )
                ->setParameter( 'admin', $admin );

        if( $domain )
            $qb->andWhere( 'a.Domain = ?2' )
                ->setParameter( 2, $domain );

        return $qb->getQuery()->getArrayResult();
    }

    /**
     * Archives flagged autoprune=1. With $before set, only those archived at or
     * before that cutoff (expired); without it, every autoprune-on archive.
     * Returns Archive entities (the prune needs their maildir dest + row).
     *
     * @param \DateTime|null $before  expiry cutoff (null = all autoprune rows)
     * @return \Entities\Archive[]
     */
    public function findAutoprune( ?\DateTime $before = null )
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select( 'a' )
            ->from( '\\Entities\\Archive', 'a' )
            ->where( 'a.autoprune = true' );

        if( $before !== null )
            $qb->andWhere( 'a.archived_at <= :before' )
               ->setParameter( 'before', $before );

        return $qb->getQuery()->getResult();
    }
}
