<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;
use ViMbAdmin\Kernel\DataTable\DataTableQuery;

/**
 * Domain
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends EntityRepository<\Entities\Domain>
 */
class Domain extends EntityRepository
{
    /** @return array<string,int|string> */
    private static function requiredDomainUsageByDomain(mixed $rows): array
    {
        if (!is_array($rows)) {
            throw new \UnexpectedValueException('Domain usage query result must be an array.');
        }

        $usage = [];
        foreach ($rows as $key => $row) {
            if (!is_int($key) || !is_array($row) || count($row) !== 2
                || !isset($row['domain']) || !is_string($row['domain'])
                || !array_key_exists('bytes', $row)) {
                throw new \UnexpectedValueException('Domain usage query row has an invalid shape.');
            }
            $bytes = $row['bytes'];
            if ((!is_int($bytes) || $bytes < 0)
                && (!is_string($bytes) || preg_match('/^(0|[1-9][0-9]*)$/D', $bytes) !== 1)) {
                throw new \UnexpectedValueException('Domain usage query row has invalid bytes.');
            }
            $domainKey = strtolower($row['domain']);
            if (array_key_exists($domainKey, $usage)) {
                throw new \UnexpectedValueException('Domain usage query returned a duplicate domain.');
            }
            $usage[$domainKey] = $bytes;
        }
        return $usage;
    }

    /**
     * @param array<string,int|string> $usage
     * @return array<int,array<string,mixed>>
     */
    private static function mergeDomainUsageRows(mixed $rows, array $usage): array
    {
        if (!is_array($rows)) {
            throw new \UnexpectedValueException('Domain list rows must be an array.');
        }

        $result = [];
        foreach ($rows as $key => $row) {
            if (!is_int($key) || !is_array($row)
                || !isset($row['name']) || !is_string($row['name'])) {
                throw new \UnexpectedValueException('Domain list row has an invalid usage shape.');
            }
            $typedRow = [];
            foreach ($row as $field => $value) {
                if (!is_string($field)) {
                    throw new \UnexpectedValueException('Domain list row has an invalid usage field.');
                }
                $typedRow[$field] = $value;
            }
            $typedRow['mailboxes_size'] = $usage[strtolower($row['name'])] ?? 0;
            $result[$key] = $typedRow;
        }
        return $result;
    }

    /** @return array<int,array<string,mixed>> */
    private static function requiredDomainListRows(mixed $rows): array
    {
        if (!is_array($rows)) {
            throw new \UnexpectedValueException('Domain query result must be an array.');
        }
        $result = [];
        foreach ($rows as $key => $row) {
            if (!is_int($key) || !is_array($row)) {
                throw new \UnexpectedValueException('Domain query row has an invalid shape.');
            }
            $typedRow = [];
            foreach ($row as $field => $value) {
                if (!is_string($field)) {
                    throw new \UnexpectedValueException('Domain query row has an invalid field.');
                }
                $typedRow[$field] = $value;
            }
            $result[$key] = $typedRow;
        }
        return $result;
    }
    /**
     * Load for admin
     *
     * Loads domains for given admin. If admin is super it returns
     * all domains.
     *
     * @param \Entities\Admin $admin
     * @return \Entities\Domain[]
     */
    public function loadForAdmin($admin)
    {
        $dql = "SELECT d FROM \\Entities\\Domain d";

        if (!$admin->isSuper()) {
            $dql .= " LEFT JOIN d.Admins d2a WHERE d2a = ?1";
        }

        $dql .= " ORDER BY d.domain ASC";

        $q = $this->getEntityManager()->createQuery($dql);

        if (!$admin->isSuper()) {
            $q->setParameter(1, $admin);
        }

        return \ViMbAdmin\Kernel\Doctrine\ResultValidator::entityList(
            $q->execute(),
            \Entities\Domain::class,
            'Domain admin query'
        );
    }

    /**
     * Load as array for admin
     *
     * Its used to get domains names in mailbox add-edit drop down list.
     * It also can be used as loadForDomainList function.
     * It calls loadForDomain iterates thought domains and it can return
     * two types of arrays: id => name, or id => [ domain data ]
     *
     * @param \Entities\Admin $admin
     * @param bool $onlyNames Type of array if set to true only names will be returned, else all data.
     * @return ($onlyNames is true ? array<int,string> : array<int,array<string,mixed>>)
     */
    public function loadForAdminAsArray($admin, $onlyNames = false)
    {
        $array = [];

        if ($onlyNames) {
            $dql = 'SELECT d.id AS id, d.domain AS domain FROM \\Entities\\Domain d';
            if (!$admin->isSuper()) {
                $dql .= ' JOIN d.Admins d2a WHERE d2a = ?1';
            }
            $dql .= ' ORDER BY d.domain ASC';

            $query = $this->getEntityManager()->createQuery($dql);
            if (!$admin->isSuper()) {
                $query->setParameter(1, $admin);
            }

            $rows = $query->getArrayResult();
            foreach ($rows as $row) {
                if (!is_array($row) || !array_key_exists('id', $row)
                    || !is_int($row['id']) || !isset($row['domain']) || !is_string($row['domain'])) {
                    throw new \UnexpectedValueException('Domain choices query row has an invalid shape.');
                }
                $array[$row['id']] = $row['domain'];
            }

        } else {
            foreach ($this->loadForAdmin($admin) as $domain) {
                $array[ $domain->requiredId() ] = [
                    'domain'        => $domain->requiredDomainName(),
                    'description'   => $domain->getDescription(),
                    'max_aliaseses' => $domain->getMaxAliases(),
                    'alias_count'   => $domain->getAliasCount(),
                    'max_mailboxes' => $domain->getMaxMailboxes(),
                    'alias_mailbox' => $domain->getMailboxCount(),
                    'max_quota'     => $domain->getMaxQuota(),
                    'quota'         => $domain->requiredQuota(),
                    'transport'     => $domain->getTransport(),
                    'active'        => $domain->getActive(),
                    'homedir'       => $domain->getHomedir(),
                    'maildir'       => $domain->getMaildir(),
                    'uid'           => $domain->getUid(),
                    'gid'           => $domain->getGid()

                ];
            }
        }
        return $array;
    }

    /**
     * Load data for domains list
     *
     * Loads information for domains list.
     *
     * @param \Entities\Admin $admin
     * @return array<int,array<string,mixed>>
     */
    public function loadForDomainList($admin)
    {
        $dql = "SELECT d.id AS id, d.domain AS name, d.alias_count AS aliases, d.mailbox_count AS mailboxes,
                    d.max_aliases AS maxaliases, d.max_mailboxes AS maxmailboxes,
                    d.max_quota AS maxquota, d.quota AS quota, d.transport AS transport, d.backupmx AS backupmx,
                    d.active AS active, d.created AS created
                FROM \\Entities\\Domain d LEFT JOIN d.Mailboxes m";

        // FIXME a.address != a.goto

        if (!$admin->isSuper()) {
            $dql .= " LEFT JOIN d.Admins d2a WHERE d2a = ?1";
        }

        $dql .= " GROUP BY d.id ORDER BY d.domain ASC";

        $q = $this->getEntityManager()->createQuery($dql);

        if (!$admin->isSuper()) {
            $q->setParameter(1, $admin);
        }

        return $this->_mergeDomainUsage(self::requiredDomainListRows($q->getArrayResult()));
    }

    /**
     * One page of the domain list for DataTables server-side processing.
     *
     * Same fields/scope as {@see loadForDomainList} but searched, ordered and
     * LIMIT/OFFSET in SQL. The alias/mailbox counts are denormalised columns on
     * the domain row, so no GROUP BY / mailbox join is needed (unlike the legacy
     * list query). `COUNT(DISTINCT d.id)` for the non-super `d.Admins` fan-out.
     *
     * @param \Entities\Admin $admin
     * @return array{rows: array<int,array<string,mixed>>, total: int, filtered: int}
     */
    public function pagedForDomainList($admin, string $search, bool $contains, string $sortField, string $sortDir, int $start, int $length)
    {
        $base = function () use ($admin): \Doctrine\ORM\QueryBuilder {
            $qb = $this->getEntityManager()->createQueryBuilder()
                ->from('\\Entities\\Domain', 'd');

            if (!$admin->isSuper()) {
                $qb->join('d.Admins', 'd2a')->andWhere('d2a = :admin')->setParameter('admin', $admin);
            }

            return $qb;
        };

        $applySearch = function (\Doctrine\ORM\QueryBuilder $qb) use ($search, $contains): \Doctrine\ORM\QueryBuilder {
            if ($search !== '') {
                $qb->andWhere('( d.domain LIKE :s OR d.description LIKE :s OR d.transport LIKE :s )')
                   ->setParameter('s', DataTableQuery::likePattern($search, $contains));
            }
            return $qb;
        };

        // Unfiltered total stable per admin -> cache briefly.
        $scopeKey = 'vimb_total_dom_' . $admin->getId();
        $total    = (int) $base()->select('COUNT(DISTINCT d.id)')->getQuery()
            ->enableResultCache(30, $scopeKey)->getSingleScalarResult();
        $filtered = $search === ''
            ? $total
            : (int) $applySearch($base())->select('COUNT(DISTINCT d.id)')->getQuery()->getSingleScalarResult();

        $sortMap = [
            'domain' => 'd.domain', 'mailboxes' => 'd.mailbox_count', 'aliases' => 'd.alias_count',
            'quota' => 'd.quota', 'active' => 'd.active', 'transport' => 'd.transport', 'created' => 'd.created',
        ];
        $orderBy = $sortMap[ $sortField ] ?? 'd.domain';

        $rows = $applySearch($base())
            ->select('d.id AS id, d.domain AS name, d.alias_count AS aliases, d.mailbox_count AS mailboxes,
                    d.max_aliases AS maxaliases, d.max_mailboxes AS maxmailboxes,
                    d.max_quota AS maxquota, d.quota AS quota, d.transport AS transport, d.backupmx AS backupmx,
                    d.active AS active, d.created AS created')
            ->orderBy($orderBy, $sortDir === 'DESC' ? 'DESC' : 'ASC')
            ->setFirstResult(max(0, $start))
            ->setMaxResults(max(1, $length))
            ->getQuery()->getArrayResult();

        return [ 'rows' => $this->_mergeDomainUsage(self::requiredDomainListRows($rows)), 'total' => $total, 'filtered' => $filtered ];
    }

    /**
     * Graft per-domain mailbox usage (`mailboxes_size`) onto a domain list array.
     *
     * Usage now comes from Dovecot's quota-clone `dovecot_quota` table
     * (Entities\Quota), keyed by full email address (username). We sum bytes
     * grouped by the domain part of the username and merge the total onto each
     * domain row. Domains with no quota rows yet report 0.
     *
     * @param array<int,array<string,mixed>> $rows Domain list rows from getArrayResult()
     * @return array<int,array<string,mixed>>
     */
    private function _mergeDomainUsage(array $rows)
    {
        if (!$rows) {
            return $rows;
        }

        // SUBSTRING_INDEX is MySQL/MariaDB-specific; username is always
        // local@domain, so take everything after the last '@'. The function in
        // GROUP BY can't use an index -> full scan of dovecot_quota, so cache
        // the aggregate (APCu result cache, 60s): usage is approximate and the
        // domain list is hit repeatedly while browsing. Native query because of
        // SUBSTRING_INDEX.
        $rsm = new \Doctrine\ORM\Query\ResultSetMapping();
        $rsm->addScalarResult('domain', 'domain', 'string');
        $rsm->addScalarResult('bytes', 'bytes', 'bigint');

        $sums = $this->getEntityManager()
            ->createNativeQuery(
                "SELECT SUBSTRING_INDEX( username, '@', -1 ) AS domain, SUM( bytes ) AS bytes
                   FROM dovecot_quota GROUP BY SUBSTRING_INDEX( username, '@', -1 )",
                $rsm
            )
            ->enableResultCache(60, 'vimb_domain_quota_sums')
            ->getResult();

        $byDomain = self::requiredDomainUsageByDomain($sums);

        return self::mergeDomainUsageRows($rows, $byDomain);
    }

    /**
     * Convenience function to purge all associations of a domain and the domain
     *
     * @param \Entities\Domain $domain The domain object
     * @return void
     */
    public function purge($domain)
    {
        $this->purgeMailboxes($domain);
        $this->purgeAliases($domain);
        $this->purgeLogs($domain);
        $this->purgeDomainAdmins($domain);

        $this->getEntityManager()->remove($domain);
        $this->getEntityManager()->flush();
    }

    /**
     * Purge all mailboxes of a domain
     *
     * @param \Entities\Domain $domain The domain to purge the mailboxes of
     * @return int The number of records deleted
     */
    public function purgeMailboxes($domain)
    {
        return \ViMbAdmin\Kernel\Doctrine\ResultValidator::affectedRows($this->getEntityManager()->createQuery(
            "DELETE FROM \\Entities\\Mailbox m WHERE m.Domain = ?1"
        )
            ->setParameter(1, $domain)
            ->execute(), 'Domain mailbox purge');
    }

    /**
     * Purge all alaises of a domain
     *
     * @param \Entities\Domain $domain The domain to purge the aliases of
     * @return int The number of records deleted
     */
    public function purgeAliases($domain)
    {
        return \ViMbAdmin\Kernel\Doctrine\ResultValidator::affectedRows($this->getEntityManager()->createQuery(
            "DELETE FROM \\Entities\\Alias m WHERE m.Domain = ?1"
        )
            ->setParameter(1, $domain)
            ->execute(), 'Domain alias purge');
    }

    /**
     * Purge all logs of a domain
     *
     * @param \Entities\Domain $domain The domain to purge the logs of
     * @return int The number of logs deleted
     */
    public function purgeLogs($domain)
    {
        return \ViMbAdmin\Kernel\Doctrine\ResultValidator::affectedRows($this->getEntityManager()->createQuery(
            "DELETE FROM \\Entities\\Log m WHERE m.Domain = ?1"
        )
            ->setParameter(1, $domain)
            ->execute(), 'Domain log purge');
    }

    /**
     * Purge all links to admins for a domain
     *
     * Requires a flush()
     *
     * @param \Entities\Domain $domain The domain to purge the admin links of
     * @return int The number of links deleted
     */
    public function purgeDomainAdmins($domain)
    {
        $count = 0;
        foreach ($domain->getAdmins() as $a) {
            $domain->removeAdmin($a);
            $count++;
        }

        return $count;
    }

    /**
     * Finds all domains which are not assigned with admin.
     *
     * Finds all domains and iterate through then making an array of 'id' => 'domain'
     * If domain inactive domain name will be append by '(inactive)' then we iterate
     * through admin domains and removing all array elements which id is already in admin domains list.
     *
     * @param \Entities\Admin $admin Admin to look for not assign domains
     * @return array<int,string>
     */
    public function getNotAssignedForAdmin($admin)
    {
        $domainNames = [];
        foreach ($this->findAll() as $domain) {
            $domainName = $domain->requiredDomainName();
            $domainNames[ $domain->requiredId() ] = $domain->getActive() ? $domainName : $domainName . " (inactive)";
        }

        foreach ($admin->getDomains() as $domain) {
            if (isset($domainNames[ $domain->requiredId() ])) {
                unset($domainNames[ $domain->requiredId() ]);
            }
        }

        return $domainNames;
    }

}
