<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use ViMbAdmin\Kernel\DataTable\DataTableQuery;

/**
 * Log
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends EntityRepository<\Entities\Log>
 */
class Log extends EntityRepository
{
    /**
     * @return array<int,array{id:mixed,action:mixed,data:mixed,timestamp:mixed,admin:mixed,domain:mixed}>
     */
    private static function requiredLogListRows(mixed $rows): array
    {
        if (!is_array($rows)) {
            throw new \UnexpectedValueException('Log query result must be an array.');
        }

        $result = [];
        $fields = ['id', 'action', 'data', 'timestamp', 'admin', 'domain'];
        foreach ($rows as $key => $row) {
            if (!is_int($key) || !is_array($row)) {
                throw new \UnexpectedValueException('Log query row has an invalid shape.');
            }
            foreach ($fields as $field) {
                if (!array_key_exists($field, $row)) {
                    throw new \UnexpectedValueException('Log query row has an invalid shape.');
                }
            }
            $result[$key] = [
                'id' => $row['id'], 'action' => $row['action'], 'data' => $row['data'],
                'timestamp' => $row['timestamp'], 'admin' => $row['admin'], 'domain' => $row['domain'],
            ];
        }
        return $result;
    }

    /**
     * Load logs for log list .
     *
     * @param \Entities\Admin|null $admin Admin for filtering mailboxes.
     * @param \Entities\Domain|null $domain Domain for filtering mailboxes.
     * @return array<int,array{id:mixed,action:mixed,data:mixed,timestamp:mixed,admin:mixed,domain:mixed}>
     */
    public function loadForLogList($admin, $domain = null)
    {
        return self::requiredLogListRows(
            $this->logListQuery($admin, $domain)->getQuery()->getArrayResult()
        );
    }

    private function logListQuery(?\Entities\Admin $admin, ?\Entities\Domain $domain): QueryBuilder
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('l.id as id , l.action as action, l.data as data, l.timestamp as timestamp, a.username as admin, d.domain as domain')
            ->from('\\Entities\\Log', 'l')
            ->leftJoin('l.Domain', 'd')
            ->join('l.Admin', 'a');

        if ($admin) {
            $qb->join('d.Admins', 'd2a')
                ->where('d2a = ?1')
                ->setParameter(1, $admin);
        }

        if ($domain) {
            $qb->andWhere('l.Domain = ?2')
                ->setParameter(2, $domain);
        }

        return $qb;
    }

    /**
     * One page of the log list for DataTables server-side processing.
     *
     * The log table grows unbounded, so this never materialises the whole set:
     * it applies the global search, ORDER BY and LIMIT/OFFSET in SQL and returns
     * the page plus total / filtered counts. Search binds a parameter; the sort
     * field is whitelisted by the caller. `COUNT(DISTINCT l.id)` because the
     * non-system `d.Admins` join fans rows out.
     *
     * @param \Entities\Admin|null  $admin   null = system/super scope (all)
     * @param \Entities\Domain|null $domain
     * @return array{rows: array<int,array{id:mixed,action:mixed,data:mixed,timestamp:mixed,admin:mixed,domain:mixed}>, total: int, filtered: int}
     */
    public function pagedForLogList($admin, $domain, string $search, bool $contains, string $sortField, string $sortDir, int $start, int $length)
    {
        // Unfiltered total stable per scope -> cache briefly (the log is large).
        $scopeKey = 'vimb_total_log_' . (is_object($admin) ? $admin->getId() : 0) . '_' . ($domain ? $domain->requiredId() : 0);
        $total    = (int) $this->logCountQuery($admin, $domain, '', $contains)->getQuery()
            ->enableResultCache(30, $scopeKey)->getSingleScalarResult();
        $filtered = $search === ''
            ? $total
            : (int) $this->logCountQuery($admin, $domain, $search, $contains)->getQuery()->getSingleScalarResult();

        $rows = self::requiredLogListRows(
            $this->pagedLogRowsQuery($admin, $domain, $search, $contains, $sortField, $sortDir, $start, $length)
                ->getQuery()->getArrayResult()
        );

        return [ 'rows' => $rows, 'total' => $total, 'filtered' => $filtered ];
    }

    private function scopedLogQuery(?\Entities\Admin $admin, ?\Entities\Domain $domain): QueryBuilder
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->from('\\Entities\\Log', 'l')
            ->leftJoin('l.Domain', 'd')
            ->join('l.Admin', 'a');

        if ($admin) {
            $qb->join('d.Admins', 'd2a')->andWhere('d2a = :admin')->setParameter('admin', $admin);
        }

        if ($domain) {
            $qb->andWhere('l.Domain = :domain')->setParameter('domain', $domain);
        }

        return $qb;
    }

    private function applyLogSearch(QueryBuilder $qb, string $search, bool $contains): QueryBuilder
    {
        if ($search !== '') {
            $qb->andWhere('( l.action LIKE :s OR a.username LIKE :s OR d.domain LIKE :s )')
               ->setParameter('s', DataTableQuery::likePattern($search, $contains));
        }
        return $qb;
    }

    private function logCountQuery(?\Entities\Admin $admin, ?\Entities\Domain $domain, string $search, bool $contains): QueryBuilder
    {
        return $this->applyLogSearch($this->scopedLogQuery($admin, $domain), $search, $contains)
            ->select('COUNT(DISTINCT l.id)');
    }

    private function pagedLogRowsQuery(?\Entities\Admin $admin, ?\Entities\Domain $domain, string $search, bool $contains, string $sortField, string $sortDir, int $start, int $length): QueryBuilder
    {
        $sortMap = [ 'action' => 'l.action', 'admin' => 'a.username', 'domain' => 'd.domain', 'timestamp' => 'l.timestamp' ];
        $orderBy = $sortMap[ $sortField ] ?? 'l.timestamp';

        return $this->applyLogSearch($this->scopedLogQuery($admin, $domain), $search, $contains)
            ->select('l.id as id, l.action as action, l.data as data, l.timestamp as timestamp, a.username as admin, d.domain as domain')
            ->orderBy($orderBy, $sortDir === 'ASC' ? 'ASC' : 'DESC')
            ->setFirstResult(max(0, $start))
            ->setMaxResults(max(1, $length));
    }
}
