<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use ViMbAdmin\Kernel\DataTable\DataTableQuery;

/**
 * Mailbox
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends EntityRepository<\Entities\Mailbox>
 * @phpstan-type MailboxHydrationRow array{id:int,username:string,name:string|null,active:bool,quota:int|string,domain:string,delete_pending:bool|null}
 * @phpstan-type MailboxListRow array{id:int,username:string,name:string|null,active:bool,quota:int|string,domain:string,delete_pending:bool|null,quota_bytes:int|string|null,quota_messages:int|string|null,last_login:int|string|null}
 */
class Mailbox extends EntityRepository
{
    /** @return int|string */
    private static function requiredUsageCount(mixed $value, string $label): int|string
    {
        if ((!is_int($value) || $value < 0)
            && (!is_string($value) || preg_match('/^(0|[1-9][0-9]*)$/D', $value) !== 1)) {
            throw new \UnexpectedValueException("Mailbox {$label} has an invalid value.");
        }
        return $value;
    }

    /** @return int|string */
    private static function requiredLastLoginTimestamp(mixed $value): int|string
    {
        return self::requiredUsageCount($value, 'last-login timestamp');
    }

    /** @return array{username:string,bytes:mixed,messages:mixed} */
    private static function requiredQuotaUsageRow(mixed $key, mixed $row): array
    {
        if (!is_int($key) || !is_array($row) || count($row) !== 3
            || !isset($row['username']) || !is_string($row['username'])
            || !array_key_exists('bytes', $row) || !array_key_exists('messages', $row)) {
            throw new \UnexpectedValueException('Mailbox quota query row has an invalid shape.');
        }
        return ['username' => $row['username'], 'bytes' => $row['bytes'], 'messages' => $row['messages']];
    }

    /** @return array<string,array{bytes:int|string,messages:int|string}> */
    private static function requiredQuotaUsageByUsername(mixed $rows): array
    {
        if (!is_array($rows)) {
            throw new \UnexpectedValueException('Mailbox quota query result must be an array.');
        }

        $usage = [];
        foreach ($rows as $key => $row) {
            $row = self::requiredQuotaUsageRow($key, $row);
            $username = strtolower($row['username']);
            if (array_key_exists($username, $usage)) {
                throw new \UnexpectedValueException('Mailbox quota query returned a duplicate username.');
            }
            $usage[$username] = [
                'bytes' => self::requiredUsageCount($row['bytes'], 'quota bytes'),
                'messages' => self::requiredUsageCount($row['messages'], 'quota messages'),
            ];
        }
        return $usage;
    }

    /** @return array{username:string,last_login:mixed} */
    private static function requiredLastLoginRow(mixed $key, mixed $row): array
    {
        if (!is_int($key) || !is_array($row) || count($row) !== 2
            || !isset($row['username']) || !is_string($row['username'])
            || !array_key_exists('last_login', $row)) {
            throw new \UnexpectedValueException('Mailbox last-login query row has an invalid shape.');
        }
        return ['username' => $row['username'], 'last_login' => $row['last_login']];
    }

    /** @return array<string,int|string> */
    private static function requiredLastLoginByUsername(mixed $rows): array
    {
        if (!is_array($rows)) {
            throw new \UnexpectedValueException('Mailbox last-login query result must be an array.');
        }

        $logins = [];
        foreach ($rows as $key => $row) {
            $row = self::requiredLastLoginRow($key, $row);
            $username = strtolower($row['username']);
            if (array_key_exists($username, $logins)) {
                throw new \UnexpectedValueException('Mailbox last-login query returned a duplicate username.');
            }
            $logins[$username] = self::requiredLastLoginTimestamp($row['last_login']);
        }
        return $logins;
    }

    /**
     * @param array<int,MailboxHydrationRow> $rows
     * @param array<string,array{bytes:int|string,messages:int|string}> $quotaByUsername
     * @param array<string,int|string> $loginByUsername
     * @return array<int,MailboxListRow>
     */
    private static function mergeMailboxUsageRows(array $rows, array $quotaByUsername, array $loginByUsername): array
    {
        $result = [];
        foreach ($rows as $key => $row) {
            $username = strtolower($row['username']);
            $quota = $quotaByUsername[$username] ?? null;
            $lastLogin = $loginByUsername[$username] ?? 0;
            $hasLastLogin = is_int($lastLogin) ? $lastLogin > 0 : $lastLogin !== '0';
            $result[$key] = [
                'id' => $row['id'], 'username' => $row['username'], 'name' => $row['name'],
                'active' => $row['active'], 'quota' => $row['quota'], 'domain' => $row['domain'],
                'delete_pending' => $row['delete_pending'],
                'quota_bytes' => $quota['bytes'] ?? null,
                'quota_messages' => $quota['messages'] ?? null,
                'last_login' => $hasLastLogin ? $lastLogin : null,
            ];
        }
        return $result;
    }

    /** @return array<int,MailboxHydrationRow> */
    private static function requiredMailboxHydrationRows(mixed $rows): array
    {
        if (!is_array($rows)) {
            throw new \UnexpectedValueException('Mailbox query result must be an array.');
        }
        $result = [];
        foreach ($rows as $key => $row) {
            if (!is_int($key) || !is_array($row)
                || !isset($row['id']) || !is_int($row['id'])
                || !isset($row['username']) || !is_string($row['username'])
                || !array_key_exists('name', $row) || (!is_string($row['name']) && $row['name'] !== null)
                || !array_key_exists('active', $row) || !is_bool($row['active'])
                || !isset($row['quota']) || (!is_int($row['quota']) && !is_string($row['quota']))
                || !isset($row['domain']) || !is_string($row['domain'])
                || !array_key_exists('delete_pending', $row)
                || (!is_bool($row['delete_pending']) && $row['delete_pending'] !== null)) {
                throw new \UnexpectedValueException('Mailbox query row has an invalid shape.');
            }
            $result[$key] = [
                'id' => $row['id'], 'username' => $row['username'], 'name' => $row['name'],
                'active' => $row['active'], 'quota' => $row['quota'], 'domain' => $row['domain'],
                'delete_pending' => $row['delete_pending'],
            ];
        }
        return $result;
    }
    /** @return array<int,array{id:int|string,username:string}> */
    private static function requiredUsernameRows(mixed $rows): array
    {
        if (!is_array($rows)) {
            throw new \UnexpectedValueException('Mailbox username query result must be an array.');
        }
        $result = [];
        foreach ($rows as $key => $row) {
            if (!is_int($key) || !is_array($row)
                || !isset($row['id'])
                || (!is_int($row['id']) && (!is_string($row['id']) || !ctype_digit($row['id'])))
                || !isset($row['username']) || !is_string($row['username'])) {
                throw new \UnexpectedValueException('Mailbox username query row has an invalid shape.');
            }
            $result[$key] = ['id' => $row['id'], 'username' => $row['username']];
        }
        return $result;
    }
    /** @return array{address:string,goto:string,domain:\Entities\Domain} */
    private function requiredAliasIdentity(\Entities\Alias $alias): array
    {
        $address = $alias->getAddress();
        if ($address === null) {
            throw new \LogicException('Alias address cannot be null.');
        }

        $goto = $alias->getGoto();
        if ($goto === null) {
            throw new \LogicException('Alias goto cannot be null.');
        }

        $domain = $alias->getDomain();
        if ($domain === null) {
            throw new \LogicException('Alias domain cannot be null.');
        }

        return ['address' => $address, 'goto' => $goto, 'domain' => $domain];
    }

    /**
     * Load mailboxes for admin.
     *
     * If admin is super he gets all mailboxes.
     *
     * @param \Entities\Admin $admin Admin for filtering mailboxes.
     * @return \Entities\Mailbox[]
     */
    public function loadForAdmin($admin)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('m')
            ->from('\\Entities\\Mailbox', 'm');

        if (!$admin->isSuper()) {
            $qb->join('m.Domain', 'd')
                ->join('d.Admins', 'd2a')
                ->where('d2a.Admin = ?1')
                ->setParameter(1, $admin);
        }

        return \ViMbAdmin\Kernel\Doctrine\ResultValidator::entityList(
            $qb->getQuery()->getResult(),
            \Entities\Mailbox::class,
            'Mailbox admin query'
        );
    }

    /**
     * Load mailboxes for mailbox list .
     *
     * If admin is super he gets all mailboxes.
     *
     * @param \Entities\Admin       $admin  Admin for filtering mailboxes.
     * @param \Entities\Domain|null $domain Domain for filtering mailboxes.
     * @return array<int,MailboxListRow>
     */
    public function loadForMailboxList($admin, $domain = null)
    {
        return $this->_mergeQuotaUsage(self::requiredMailboxHydrationRows(
            $this->mailboxListQuery($admin, $domain)->getQuery()->getArrayResult()
        ));
    }

    private function mailboxListQuery(\Entities\Admin $admin, ?\Entities\Domain $domain): QueryBuilder
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('m.id as id, m.username as username, m.name as name, m.active as active,
                    m.quota as quota, d.domain as domain, m.delete_pending')
            ->from('\\Entities\\Mailbox', 'm')
            ->where('m.delete_pending = FALSE')
            ->join('m.Domain', 'd');

        if (!$admin->isSuper()) {
            $qb->join('d.Admins', 'd2a')
                ->andWhere('d2a = ?1')
                ->setParameter(1, $admin);
        }

        if ($domain) {
            $qb->andWhere('m.Domain = ?2')
                ->setParameter(2, $domain);
        }

        return $qb;
    }

    /**
     * One page of the mailbox list for DataTables server-side processing.
     *
     * Same scope as {@see loadForMailboxList} (active, admin/domain filtered) but
     * applies the global search, ORDER BY, and LIMIT/OFFSET in SQL and returns
     * the page plus the total / filtered counts the protocol needs. Search binds
     * a parameter (no string interpolation) and the sort field is whitelisted by
     * the caller. `COUNT(DISTINCT m.id)` because the non-super `d.Admins` join
     * fans rows out.
     *
     * @param \Entities\Admin       $admin
     * @param \Entities\Domain|null $domain
     * @return array{rows: list<array<string,mixed>>, total: int, filtered: int}
     */
    public function pagedForMailboxList($admin, $domain, string $search, bool $contains, string $sortField, string $sortDir, int $start, int $length)
    {
        $base = function () use ($admin, $domain): \Doctrine\ORM\QueryBuilder {
            $qb = $this->getEntityManager()->createQueryBuilder()
                ->from('\\Entities\\Mailbox', 'm')
                ->where('m.delete_pending = FALSE')
                ->join('m.Domain', 'd');

            if (!$admin->isSuper()) {
                $qb->join('d.Admins', 'd2a')->andWhere('d2a = :admin')->setParameter('admin', $admin);
            }

            if ($domain) {
                $qb->andWhere('m.Domain = :domain')->setParameter('domain', $domain);
            }

            return $qb;
        };

        $applySearch = function (\Doctrine\ORM\QueryBuilder $qb) use ($search, $contains): \Doctrine\ORM\QueryBuilder {
            if ($search !== '') {
                $qb->andWhere('( m.username LIKE :s OR m.name LIKE :s OR d.domain LIKE :s )')
                   ->setParameter('s', DataTableQuery::likePattern($search, $contains));
            }
            return $qb;
        };

        // Unfiltered total is stable per scope and hit on every paging draw -> cache it briefly.
        $scopeKey = 'vimb_total_mb_' . $admin->getId() . '_' . ($domain ? $domain->requiredId() : 0);
        $total    = (int) $base()->select('COUNT(DISTINCT m.id)')->getQuery()
            ->enableResultCache(30, $scopeKey)->getSingleScalarResult();
        // No search -> filtered == total; skip the second COUNT entirely.
        $filtered = $search === ''
            ? $total
            : (int) $applySearch($base())->select('COUNT(DISTINCT m.id)')->getQuery()->getSingleScalarResult();

        $sortMap = [ 'username' => 'm.username', 'name' => 'm.name', 'quota' => 'm.quota', 'domain' => 'd.domain', 'active' => 'm.active' ];
        $orderBy = $sortMap[ $sortField ] ?? 'm.username';

        $rows = $applySearch($base())
            ->select('m.id as id, m.username as username, m.name as name, m.active as active,
                    m.quota as quota, d.domain as domain, m.delete_pending')
            ->orderBy($orderBy, $sortDir === 'DESC' ? 'DESC' : 'ASC')
            ->setFirstResult(max(0, $start))
            ->setMaxResults(max(1, $length))
            ->getQuery()->getArrayResult();

        return [ 'rows' => array_values($this->_mergeQuotaUsage(self::requiredMailboxHydrationRows($rows))), 'total' => $total, 'filtered' => $filtered ];
    }

    /**
     * Merge live Dovecot quota-clone usage into a mailbox list array.
     *
     * The `dovecot_quota` table (Entities\Quota) is populated by Dovecot's
     * quota-clone plugin and keyed by username. It has no mailbox id, so we batch-load every
     * row for the usernames in $rows and graft `quota_bytes` / `quota_messages`
     * onto each. Both default to null when the plugin has not yet written a row
     * (e.g. a brand new mailbox), in which case the view shows 0 until Dovecot
     * writes the first usage figure.
     *
     * @param array<int,MailboxHydrationRow> $rows Mailbox list rows from getArrayResult()
     * @return array<int,MailboxListRow>
     */
    private function _mergeQuotaUsage(array $rows)
    {
        if (!$rows) {
            return $rows;
        }

        $usernames = array_column($rows, 'username');

        $quotas = $this->getEntityManager()->createQueryBuilder()
            ->select('q.username as username, q.bytes as bytes, q.messages as messages')
            ->from('\\Entities\\Quota', 'q')
            ->where('q.username IN ( :usernames )')
            ->setParameter('usernames', $usernames)
            ->getQuery()->getArrayResult();

        $byUser = self::requiredQuotaUsageByUsername($quotas);

        // Last-login (Dovecot last_login plugin -> dovecot_last_login table,
        // unix timestamp). Batch-load and graft alongside the quota usage.
        $logins = $this->getEntityManager()->createQueryBuilder()
            ->select('l.username as username, l.last_login as last_login')
            ->from('\\Entities\\LastLogin', 'l')
            ->where('l.username IN ( :usernames )')
            ->setParameter('usernames', $usernames)
            ->getQuery()->getArrayResult();

        $loginByUser = self::requiredLastLoginByUsername($logins);

        return self::mergeMailboxUsageRows($rows, $byUser, $loginByUser);
    }

    /**
     * Load mailboxes usernmae list.
     *
     * If admin is super he gets all mailboxes.
     *
     * @param \Entities\Admin       $admin  Admin for filtering mailboxes.
     * @param \Entities\Domain|null $domain Domain for filtering mailboxes.
     * @return array<int|string,string>
     */
    public function loadUsernameList($admin, $domain = null)
    {
        return $this->indexUsernameRows(self::requiredUsernameRows(
            $this->usernameListQuery($admin, $domain)->getQuery()->getArrayResult()
        ));
    }

    private function usernameListQuery(\Entities\Admin $admin, ?\Entities\Domain $domain): QueryBuilder
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('m.id as id , m.username as username')
            ->from('\\Entities\\Mailbox', 'm')
            ->join('m.Domain', 'd');

        if (!$admin->isSuper()) {
            $qb->join('d.Admins', 'd2a')
                ->where('d2a.Admin = ?1')
                ->setParameter(1, $admin);
        }

        if ($domain) {
            $qb->andWhere('m.Domain = ?2')
                ->setParameter(2, $domain);
        }

        return $qb;
    }

    /**
     * @param array<int,array{id:int|string,username:string}> $data
     * @return array<int|string,string>
     */
    private function indexUsernameRows(array $data): array
    {
        $result = [];
        foreach ($data as $row) {
            $result[ $row['id'] ] = $row['username'];
        }
        return $result;
    }


    /**
     * Check if mailbox is unique.
     *
     * Splits given email to local part and domain ant count all mailboxes
     * with these parameters. If count is 0 then function returns true else false.
     *
     * @param string $email Email to check
     * @return bool
     */
    public function isUnique($email)
    {
        list($lpart, $domain) = explode('@', $email);

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('count( m.id )')
            ->from('\\Entities\\Mailbox', 'm')
            ->join('m.Domain', 'd')
            ->where('m.local_part = ?1')
            ->andWhere('d.domain = ?2')
            ->setParameter(1, $lpart)
            ->setParameter(2, $domain);

        return $qb->getQuery()->getSingleScalarResult() > 0 ? false : true;
    }

    /**
     * Purges mailbox
     *
     * Remove all mailbox preferences.
     * Remove all mailbox aliases with their preferences and decrease alias count in domain.
     * Remove mailbox entry for multi alias with multi addresses.
     * Remove actual mailbox and decrease mailbox count i domain.
     * Returns false if privileges not allowed and true if removed.
     *
     * @param \Entities\Mailbox $mailbox Mailbox to purge
     * @param \Entities\Admin|null $admin Admin which purging mailbox for privilege validation,
     *                                     or null for a trusted system context.
     * @param bool $removeMailbox If true, also remove the Mailbox entity. If false, purge everything but this entity.
     * @return bool
     */
    public function purgeMailbox($mailbox, $admin, $removeMailbox = true)
    {
        $domain = $mailbox->getDomain();
        if ($domain === null) {
            throw new \LogicException('Mailbox domain cannot be null.');
        }

        // A null admin == trusted system context (CLI/queue runner): skip the
        // per-admin ownership check. A non-null admin must own the domain (or
        // be super) to purge.
        if ($admin !== null && !$admin->isSuper() && !$domain->getAdmins()->contains($admin)) {
            return false;
        }

        $username = $mailbox->requiredUsername();

        $aliasRepository = $this->getEntityManager()->getRepository("\\Entities\\Alias");
        if (!$aliasRepository instanceof \Repositories\Alias) {
            throw new \LogicException('Alias entity must use Repositories\\Alias.');
        }
        $aliases = $aliasRepository->loadForMailbox($mailbox, $admin, true);
        $inAliases = $aliasRepository->loadWithMailbox($mailbox, $admin);

        /** @var array<int,array{address:string,goto:string,domain:\Entities\Domain}> $aliasIdentities */
        $aliasIdentities = [];
        foreach ($aliases as $alias) {
            $aliasIdentities[ spl_object_id($alias) ] = $this->requiredAliasIdentity($alias);
        }
        foreach ($inAliases as $alias) {
            $aliasIdentities[ spl_object_id($alias) ] = $this->requiredAliasIdentity($alias);
        }

        foreach ($mailbox->getPreferences() as $pref) {
            $this->getEntityManager()->remove($pref);
        }

        //this won't delete the alias entry where address == goto
        foreach ($aliases as $alias) {
            $this->_removeAlias($alias, $aliasIdentities[ spl_object_id($alias) ]);
        }

        foreach ($inAliases as $alias) {
            $identity = $aliasIdentities[ spl_object_id($alias) ];
            $gotos = explode(',', $identity['goto']);

            foreach ($gotos as $key => $goto) {
                $gotos[ $key ] = $goto = trim($goto);

                if (($goto == $username) || ($goto == '')) {
                    unset($gotos[ $key ]);
                }
            }

            if (sizeof($gotos) == 0) {
                $this->_removeAlias($alias, $identity);
            } else {
                $alias->setGoto(implode(',', $gotos));
            }
        }

        if ($removeMailbox) {
            $this->getEntityManager()->remove($mailbox);
        }

        $domain->decreaseMailboxCount();

        return true;
    }

    /**
     * Removes alias
     *
     * Removes alias and its preferences also decrease domains alias count
     * if alias goto field is not equal to alias address field.
     *
     * @param \Entities\Alias $alias Alias to remove.
     * @param array{address:string,goto:string,domain:\Entities\Domain} $identity Validated alias identity.
     * @return bool
     */
    private function _removeAlias($alias, array $identity)
    {
        foreach ($alias->getPreferences() as $pref) {
            $this->getEntityManager()->remove($pref);
        }

        $this->getEntityManager()->remove($alias);

        if ($identity['goto'] != $identity['address']) {
            $identity['domain']->decreaseAliasCount();
        }

        return true;
    }

    /**
     * Find all mailboxes pending deletion.
     *
     * @return \Entities\Mailbox[]
     */
    public function pendingDelete()
    {
        $result = $this->getEntityManager()->createQueryBuilder()
            ->select('m')
            ->from('\\Entities\\Mailbox', 'm')
            ->where('m.delete_pending = TRUE')
            ->getQuery()
            ->getResult();

        return \ViMbAdmin\Kernel\Doctrine\ResultValidator::entityList(
            $result,
            \Entities\Mailbox::class,
            'Pending mailbox deletion query'
        );
    }

}
