<div id="form_div_change_mailbox_pwd">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="form-horizontal">
        {$element->csrf nofilter}

        {$element->username nofilter}
        {$element->current_password nofilter}
        {$element->new_password nofilter}
        {$element->confirm_new_password nofilter}

        <fieldset class="form-actions">
            <a class="btn" href="{genUrl controller='auth' action='login'}" >Cancel</a>
            &nbsp;
            <input class="btn btn-primary" type="submit" id="{$element->change->getId()}" value="{$element->change->getLabel()}" />
        </fieldset>
    </form>

</div>
