{tmplinclude file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >
        <h1>Lost Password</h1>
    </div>


    {OSS_Message}


    <div class="row">

        <div class="span6 offset3">

        	<img src="{genUrl}/images/logo_500x159.jpg" />

{if isset( $useCaptcha ) && $useCaptcha}
            <p>
                Please enter the characters from the image below into the
                verification box. Click the image for a different one.
            </p>
            <img id="captchaimage" style="cursor: pointer;" title="Click for a new image"
                 src="{genUrl controller='auth' action='captcha-image' id=$captchaId}" />
{/if}

            {$formHtml nofilter}

            <div class="well">

                <p>
                    Are you a user (mailbox owner) looking to change your <br />
                    password? If so, please click on this button:

                    <a style="float: right;" class="btn btn-primary" href="{genUrl controller="auth" action="change-password"}">Mailbox Password Change</a>
                </p>

            </div>


        </div>
    </div>

{if isset( $useCaptcha ) && $useCaptcha}
<script type="text/javascript">
    document.getElementById('captchaimage').addEventListener('click', function() {
        var r = document.getElementById('requestnewimage');
        r.value = '1';
        r.form.submit();
    });
</script>
{/if}
</div>

{tmplinclude file="footer.phtml"}
