{tmplinclude file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >
        <h1>Change Password</h1>
    </div>

{OSS_Message}

<div class="row">
    <div class="span6 offset3">

        <p>Change the password for your mailbox. Enter your email address, your
           current password, and the new password twice.</p>

        {$formHtml nofilter}

    </div>
</div>

</div>

{tmplinclude file="footer.phtml"}
