<div class="modal-header">
    <h3 class="modal-title">Email Settings</h3>
       <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body" id="esbody">
    <p>Email settings for '<em>{$mailbox->requiredUsername()}</em>'.</p>

{if isset( $esError ) && $esError}
    <div class="alert alert-danger">{$esError|escape}</div>
{/if}

    <form action="{genUrl controller='mailbox' action='email-settings' mid=$mailbox->getId()}/send/1"
          method="post" id="email_settings_form" name="email_settings_form" class="form-horizontal">

        <input type="hidden" name="csrf" value="{$csrfToken}" />

        <div style="position: fixed; z-index: 1;">
            <select name="type" id="type" class="form-select" required title="Email">
{foreach $typeOptions as $optValue => $optLabel}
                <option value="{$optValue|escape}"{if $optValue == $selectedType} selected="selected"{/if}>{$optLabel|escape}</option>
{/foreach}
            </select>
        </div>

        <div class="control-group">
            <label class="control-label optional">&nbsp;</label>
            <div class="controls"></div>
        </div>

        <div id="other_email" {if $selectedType != 'other'}style="display: none"{/if}>
            <input type="text" name="email" id="email" size="32" class="form-control"{if $selectedType == 'other'} required{/if}
                   placeholder="email1@example.com,email2@example.com" value="{$emailValue|escape}" />
        </div>

    </form>
</div>

<div class="modal-footer" id="esfooter">
    <button id="modal_dialog_save" class="btn btn-primary">Send</button>
    <button id="modal_dialog_cancel" class="btn">Close</button>
</div>
