<?php

namespace Proxies\__CG__\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MailboxTask extends \Entities\MailboxTask implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'id', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'type', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'username', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'status', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'priority', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'created_at', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'started_at', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'finished_at', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'log', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'data', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'Domain', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'RequestedBy'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'id', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'type', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'username', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'status', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'priority', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'created_at', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'started_at', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'finished_at', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'log', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'data', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'Domain', '' . "\0" . 'Entities\\MailboxTask' . "\0" . 'RequestedBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MailboxTask $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$v]);

        return parent::setType($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$v]);

        return parent::setUsername($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$v]);

        return parent::setStatus($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriority()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriority', []);

        return parent::getPriority();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriority($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriority', [$v]);

        return parent::setPriority($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$v]);

        return parent::setCreatedAt($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartedAt', []);

        return parent::getStartedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartedAt($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartedAt', [$v]);

        return parent::setStartedAt($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinishedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinishedAt', []);

        return parent::getFinishedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinishedAt($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinishedAt', [$v]);

        return parent::setFinishedAt($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getLog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLog', []);

        return parent::getLog();
    }

    /**
     * {@inheritDoc}
     */
    public function setLog($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLog', [$v]);

        return parent::setLog($v);
    }

    /**
     * {@inheritDoc}
     */
    public function appendLog($line)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'appendLog', [$line]);

        return parent::appendLog($line);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$v]);

        return parent::setData($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', []);

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain(?\Entities\Domain $v = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', [$v]);

        return parent::setDomain($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestedBy', []);

        return parent::getRequestedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequestedBy(?\Entities\Admin $v = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequestedBy', [$v]);

        return parent::setRequestedBy($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeLabel', []);

        return parent::getTypeLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusLabel', []);

        return parent::getStatusLabel();
    }

}
