<?php

namespace Proxies\__CG__\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class McpToken extends \Entities\McpToken implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\McpToken' . "\0" . 'id', '' . "\0" . 'Entities\\McpToken' . "\0" . 'name', '' . "\0" . 'Entities\\McpToken' . "\0" . 'token_hash', '' . "\0" . 'Entities\\McpToken' . "\0" . 'scope', '' . "\0" . 'Entities\\McpToken' . "\0" . 'allowed_ips', '' . "\0" . 'Entities\\McpToken' . "\0" . 'allowed_domains', '' . "\0" . 'Entities\\McpToken' . "\0" . 'created', '' . "\0" . 'Entities\\McpToken' . "\0" . 'expires_at', '' . "\0" . 'Entities\\McpToken' . "\0" . 'last_used_at', '' . "\0" . 'Entities\\McpToken' . "\0" . 'revoked'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\McpToken' . "\0" . 'id', '' . "\0" . 'Entities\\McpToken' . "\0" . 'name', '' . "\0" . 'Entities\\McpToken' . "\0" . 'token_hash', '' . "\0" . 'Entities\\McpToken' . "\0" . 'scope', '' . "\0" . 'Entities\\McpToken' . "\0" . 'allowed_ips', '' . "\0" . 'Entities\\McpToken' . "\0" . 'allowed_domains', '' . "\0" . 'Entities\\McpToken' . "\0" . 'created', '' . "\0" . 'Entities\\McpToken' . "\0" . 'expires_at', '' . "\0" . 'Entities\\McpToken' . "\0" . 'last_used_at', '' . "\0" . 'Entities\\McpToken' . "\0" . 'revoked'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (McpToken $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$v]);

        return parent::setName($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getTokenHash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTokenHash', []);

        return parent::getTokenHash();
    }

    /**
     * {@inheritDoc}
     */
    public function setTokenHash($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTokenHash', [$v]);

        return parent::setTokenHash($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getScope()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScope', []);

        return parent::getScope();
    }

    /**
     * {@inheritDoc}
     */
    public function setScope($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScope', [$v]);

        return parent::setScope($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowedIps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowedIps', []);

        return parent::getAllowedIps();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowedIps($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowedIps', [$v]);

        return parent::setAllowedIps($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowedDomains()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowedDomains', []);

        return parent::getAllowedDomains();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowedDomains($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowedDomains', [$v]);

        return parent::setAllowedDomains($v);
    }

    /**
     * {@inheritDoc}
     */
    public function allowsDomain($domain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allowsDomain', [$domain]);

        return parent::allowsDomain($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$v]);

        return parent::setCreated($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiresAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiresAt', []);

        return parent::getExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', [$v]);

        return parent::setExpiresAt($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUsedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUsedAt', []);

        return parent::getLastUsedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUsedAt($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUsedAt', [$v]);

        return parent::setLastUsedAt($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getRevoked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevoked', []);

        return parent::getRevoked();
    }

    /**
     * {@inheritDoc}
     */
    public function setRevoked($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevoked', [$v]);

        return parent::setRevoked($v);
    }

    /**
     * {@inheritDoc}
     */
    public function hasScope($want)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasScope', [$want]);

        return parent::hasScope($want);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive(?\DateTime $now = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', [$now]);

        return parent::isActive($now);
    }

}
